version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mohamad
      POSTGRES_DB: lifeaz

  back:
    volumes:
      - ./back/:/app/
      - /app/node_modules
      - /app/dist
    restart: always
    build: ./back/
    image: back
    ports:
      - 5000:5000
    entrypoint: "yarn dev"
    working_dir: /app
